Create My App
enjoseph/myPortfolio_React-Redux pull request #1
Opened 2023-11-23 04:00 UTC by enjoseph

2023-12-09 18:48 UTC, elchinimanov commented on src/components/Footer.js
> +                <a href="https://github.com/enjoseph"><motion.li whileHover={{ scale: 1.2 }} whileTap={{ scale: 0.8 }} className={FooterStyle.SM_icon}> <i className="fa-brands fa-github"></i> </motio
linkleri config file icherisine cixar

2023-12-09 18:49 UTC, elchinimanov commented on src/components/Modal/AboutProjectModal.js
> +  };
bunlari componentin icherisinden kenara cixar, static datadi

2023-12-09 18:53 UTC, elchinimanov commented on src/components/Modal/AboutProjectModal.js
> +import AboutProjectModalStyle from "../../style/Modal/AboutProjectModal.module.css";
burada sadece styles import edirsen.

2023-12-09 18:54 UTC, elchinimanov commented on src/components/Modal/AboutProjectModal.js
> +        {currentProject.githubLink === "" ? (
`currentProject.githubLink === ""` bunun yerine `!currentProject.githubLink`

2023-12-09 18:55 UTC, elchinimanov commented on src/components/Modal/AboutSkillModal.js
> +    if (currentSkills.lvl === counter) clearTimeout(counterCall);
return hani bes ?

2023-12-09 18:56 UTC, elchinimanov commented on src/components/Project.js
> +  };
component component icherisinde yaratma

2023-12-09 18:57 UTC, elchinimanov commented on src/components/Project.js
> +      {currentProject !== undefined ? (
qeribe yoxlamadir, currentProject ?? ( ve.s yaza bilerdin veya !currentProject

2023-12-09 18:57 UTC, elchinimanov commented on src/components/Project.js
> +        <AboutProjectModal></AboutProjectModal>
eger compnentin icherisinnde hechne yoxdursa bunu sadece `< AboutProjectModal />` yaza bilerdin,

2023-12-09 18:58 UTC, elchinimanov commented on src/components/Skills.js
> +    {currentCategory !== undefined ? (
burada eynisi `!currentCategory`

2023-12-09 18:58 UTC, elchinimanov commented on src/components/Skills.js
> +    {currentCategory !== undefined ? (
currentCategory !== undefined bele yoxlamirlar layihelerde

2023-12-09 18:59 UTC, elchinimanov commented on src/components/Skills.js
> +      <AboutModal></AboutModal>
qeyd elediyim kimi eger componentin icherisinde bir wey yoxdursa onda cut olmaq mecburiyetinde deyil tek ola bilir componnent `<AboutModal />`

2023-12-09 19:01 UTC, elchinimanov commented on src/stores/documentSlice.js
bu slice ne uchun lazimdi, data deyiwmirse bunu config file icherisine yazmaq olar

2023-12-09 19:01 UTC, elchinimanov commented on src/stores/languageSlice.js
bu slice ne uchun lazimdi, data deyiwmirse bunu config file icherisine yazmaq olar

2023-12-09 19:03 UTC, elchinimanov commented on src/stores/projectsSlice.js
burda qeyd elediyin projectler reducerin icherisinde qeyd edilmemelidi, bu static datadi, sene tek lazim olan current projectdir ki sen ona uygun static datanni sehfede display edesen, anlamasan ne deyirem yaz

2023-12-09 19:03 UTC, elchinimanov requested changes
sehfler var, meslehet gorurem redux la bagli video ve materiallar uzerinde iwleyesen , chunki tam mentiqi anlamadigini gorurem

2023-12-09 19:46 UTC, enjoseph commented on src/components/Skills.js
> +      <AboutModal></AboutModal>
Haqqlısız ferqli yanasma istifade etmisdim  ilk basda sonra yanasmani deyisdim code style duzeltmek gozumden qacib. Duzeltdim.

2023-12-09 19:47 UTC, enjoseph commented on src/components/Skills.js
> +    {currentCategory !== undefined ? (
Bunlarda hemin yanasma ile baglil idi. Duzeltirem bunlarida.

2023-12-09 19:57 UTC, enjoseph commented on src/components/Project.js
> +        <AboutProjectModal></AboutProjectModal>
Fixed.

2023-12-09 19:57 UTC, enjoseph commented on src/components/Project.js
> +      {currentProject !== undefined ? (
Fixed

2023-12-09 20:00 UTC, enjoseph commented on src/components/Modal/AboutProjectModal.js
> +        {currentProject.githubLink === "" ? (
Fixed

2023-12-09 20:01 UTC, enjoseph commented on src/components/Modal/AboutProjectModal.js
> +import AboutProjectModalStyle from "../../style/Modal/AboutProjectModal.module.css";
Fixed

2023-12-09 20:05 UTC, enjoseph commented on src/components/Modal/AboutProjectModal.js
> +  };
Tam olaraq anlamadım,  App Seviyesine çıxarım ?

2023-12-11 06:42 UTC, enjoseph commented on src/components/Footer.js
> +                <a href="https://github.com/enjoseph"><motion.li whileHover={{ scale: 1.2 }} whileTap={{ scale: 0.8 }} className={FooterStyle.SM_icon}> <i className="fa-brands fa-github"></i> </motio
fixed

2023-12-11 06:52 UTC, enjoseph commented on src/components/Project.js
> +  };
fixed

2023-12-11 06:53 UTC, enjoseph commented on src/components/Modal/AboutSkillModal.js
> +    if (currentSkills.lvl === counter) clearTimeout(counterCall);
fixed

2023-12-11 06:53 UTC, enjoseph commented on src/stores/documentSlice.js
Admin panelden documentlerimi change etmeyi dusunurem gelecekde buna yonelik yazmisam bu kodu

2023-12-11 06:54 UTC, enjoseph commented on src/stores/languageSlice.js
Fixed

2023-12-11 07:15 UTC, enjoseph commented on src/stores/projectsSlice.js
Admin panel yazacam app ucun  dusunurdum ki projectlrimde deyisen data olacaq buna gore onlari burda saxladim sonra transfer data ede bilim  api kecirecem yeni

2023-12-16 15:57 UTC, merged